#[cfg(target_os = "linux")]
pub mod cinnamon;
#[cfg(target_os = "linux")]
pub mod cutefish;
#[cfg(target_os = "linux")]
pub mod deepin;
#[cfg(target_os = "linux")]
pub mod gnome;
#[cfg(target_os = "linux")]
pub mod kde;
#[cfg(target_os = "linux")]
pub mod lxde;
#[cfg(target_os = "linux")]
pub mod lxqt;
#[cfg(target_os = "linux")]
pub mod mate;
#[cfg(target_os = "windows")]
pub mod windows;
#[cfg(target_os = "linux")]
pub mod xfce;
#[cfg(target_os = "linux")]
pub mod yoyo;
