name: Package
on: push

jobs:
  change-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1
        with:
          dev-branch: master

      - name: Change Version
        run: |
          sed -i "s/\"version\":.*/\"version\": \"${{ steps.version.outputs.version }}\",/g" package.json
          sed -i "s/\"version\":.*/\"version\": \"${{ steps.version.outputs.version }}\"/g" src-tauri/tauri.conf.json
          echo ${{ steps.version.outputs.version }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: source
          path: ./*
          if-no-files-found: error

  build:
    needs: change-version
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/download-artifact@v3
        id: download
        with:
          name: source
          
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install Tauri Dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
          echo ${{steps.download.outputs.download-path}}
          cd ${{steps.download.outputs.download-path}}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install Dependencies
        run: pnpm install

      - name: Build and Package
        run: pnpm tauri build

      - name: Upload Artifacts(deb)
        if: matrix.platform == 'ubuntu-20.04'
        uses: actions/upload-artifact@v3
        with:
          name: wallhaven-desktop.deb
          path: ${{steps.download.outputs.download-path}}/src-tauri/target/release/bundle/deb/*.deb
          if-no-files-found: error

      - name: Upload Artifacts(appimage)
        if: matrix.platform == 'ubuntu-20.04'
        uses: actions/upload-artifact@v3
        with:
          name: wallhaven-desktop.Appimage
          path: ${{steps.download.outputs.download-path}}/src-tauri/target/release/bundle/appimage/*.AppImage
          if-no-files-found: error

      - name: Upload Artifacts(msi)
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: wallhaven-desktop.msi
          path: ${{steps.download.outputs.download-path}}/src-tauri/target/release/bundle/msi/*.msi
          if-no-files-found: error

      - name: Upload Artifacts(dmg)
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: wallhaven-desktop.dmg
          path: ${{steps.download.outputs.download-path}}/src-tauri/target/release/bundle/dmg/*.dmg
          if-no-files-found: error
